### ISSUE TITLE
Move all source code to one directory

### ISSUE THREAD

**Issue by mirestrepo** [brown-ccv/tiff-volume-2png#18]
Typically all files live in one `src` directory or a directory with the name of the package -this is what we do commonly, but `src` is another fine convention

so the file structure would be ( I would also rename this package to something more generic)

```
ccv-3d-convert-tools
--- file1.py
--- file2.py
```

I think in this case the 3 directories is overkilled, just have them in a flat structure for now

**Comment by kmilo9999** [comment]
closed by #21
