### ISSUE TITLE
Integrate Typer

### ISSUE THREAD

**Issue by kmilo9999** [brown-ccv/tiff-volume-2png#3]
- Remove current progress bar and use typer's
- Modify command args processing using typer
- Use DocString the document function usage
- Equalizer argument names should be more descriptive. or perhaps make the type of equalizer a value passed to an --equalize flag

**Comment by mcmcgrath13** [comment]
@kmilo9999 could you break these out into separate issues for each category of thing? (e.g. poetry is one issue, typer another, doc strings a third)

**Comment by kmilo9999** [comment]
Issue renamed it to represent a single task to do.
